import { generateText, CoreMessage } from "ai";
import fs from "fs";
import { LLM } from "./llm.js";
import { SkillManager } from "./skills.js";
import { TOOL_SCHEMAS } from "../tools/registry.js";
import { DIRS, COWRNGLR_MD } from "./init.js";

export class Agent {
  public llm: LLM;
  public maxIterations: number;
  private skillManager: SkillManager;
  private originalPrompt: string; // Raw base prompt — never mutated
  private baseSystemPrompt: string; // Fully-built: base + memory + skills
  private messages: CoreMessage[] = []; // Does NOT hold a "system" role entry
  private allowedTools?: string[];

  constructor(
    llm: LLM,
    systemPrompt: string,
    maxIterations: number = 20,
    allowedTools?: string[],
  ) {
    this.llm = llm;
    this.maxIterations = maxIterations;
    this.allowedTools = allowedTools;
    this.skillManager = new SkillManager();
    this.originalPrompt = systemPrompt;
    this.baseSystemPrompt = this._buildSystemPrompt(systemPrompt);
    // NOTE: System prompt is passed to generateText via the `system` param,
    // NOT as a message in the messages array. Sending it both ways causes
    // double-injection and provider errors on some models.
  }

  private _buildSystemPrompt(basePrompt: string): string {
    let finalPrompt = basePrompt;

    // 1. Inject COWRNGLR.md (project-level context, highest priority — like CLAUDE.md)
    if (fs.existsSync(COWRNGLR_MD)) {
      const cowrnglrContent = fs.readFileSync(COWRNGLR_MD, "utf-8").trim();
      if (cowrnglrContent) {
        finalPrompt += `\n\n[COWRNGLR.md — PROJECT CONTEXT]\nThis file was generated by /init and may have been manually edited. Treat it as the authoritative source of truth for this project:\n---\n${cowrnglrContent}\n---`;
      }
    }

    // 2. Inject Project Memory (.cowrangler/memory.md)
    if (fs.existsSync(DIRS.local.memory)) {
      const memoryContent = fs.readFileSync(DIRS.local.memory, "utf-8").trim();
      if (memoryContent) {
        finalPrompt += `\n\n[PROJECT MEMORY]\nThe following contains authoritative facts about the project. Always respect these:\n---\n${memoryContent}\n---`;
      }
    }

    // 2. Inject available Skills
    const skills = this.skillManager.getAvailableSkills();
    if (skills.length > 0) {
      const skillsText = skills
        .map((s) => `- **${s.id}**: ${s.description}`)
        .join("\n");
      finalPrompt += `\n\n[AVAILABLE SKILLS]\nYou have the following Standard Operating Procedures (SOPs). When a user request matches one, load it with \`utilize_skill\` before starting:\n${skillsText}`;
    }

    return finalPrompt;
  }

  private getTools() {
    if (!this.allowedTools || this.allowedTools.includes("*")) {
      return TOOL_SCHEMAS;
    }
    const filtered: Record<string, any> = {};
    for (const [key, value] of Object.entries(TOOL_SCHEMAS)) {
      if (this.allowedTools.includes(key)) filtered[key] = value;
    }
    return filtered;
  }

  /**
   * Hot-swap the underlying LLM (called by /model set).
   */
  setModel(newLlm: LLM) {
    this.llm = newLlm;
  }

  /**
   * Re-read memory & skills from disk and refresh the injected system prompt.
   * Useful after /memory edit or skill additions mid-session.
   */
  refreshSystemPrompt() {
    this.baseSystemPrompt = this._buildSystemPrompt(this.originalPrompt);
  }

  async chat(
    userMessage: string,
    onToolCall?: (name: string, args: any) => void,
    onStepText?: (text: string) => void,
  ): Promise<string> {
    this.messages.push({ role: "user", content: userMessage });

    try {
      const result = await generateText({
        model: this.llm.getModel(),
        system: this.baseSystemPrompt,
        // Explicitly filter out any accidental "system" role messages —
        // the system param above is the single source of truth.
        messages: this.messages.filter((m) => m.role !== "system"),
        tools: this.getTools(),
        maxSteps: this.maxIterations,
        onStepFinish: ({ text, toolCalls }) => {
          // Surface any reasoning text the LLM emitted before/between tool calls
          if (text?.trim() && onStepText) {
            onStepText(text.trim());
          }
          if (toolCalls && onToolCall) {
            for (const call of toolCalls) {
              onToolCall(call.toolName, call.args);
            }
          }
        },
      });

      // Persist the full step history (tool calls + results + final reply)
      // so subsequent turns have complete context of what was done.
      for (const msg of result.response.messages) {
        this.messages.push(msg as CoreMessage);
      }

      return result.text;
    } catch (error) {
      // Roll back the user message to keep history consistent
      this.messages.pop();
      throw error;
    }
  }

  /**
   * Clear conversation history and rebuild the system prompt from disk.
   */
  reset(): void {
    this.baseSystemPrompt = this._buildSystemPrompt(this.originalPrompt);
    this.messages = [];
  }

  /** Number of messages in the current conversation context. */
  get contextLength(): number {
    return this.messages.length;
  }
}
